name: smoke-test
on:
  push:
    branches:
      - river

jobs:
  dev-build-ui:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./meme_ui
      - name: quasar build
        uses: borales/actions-yarn@v4
        with:
          cmd: quasar build --mode spa
          dir: ./meme_ui
      - uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_COMPRESS: xz
          GHR_PATH: ./meme_ui/dist/
          GHR_REPLACE: true
          GHR_DELETE: false

  dev-smoke-test:
    needs: dev-build-ui
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.2"]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry install --with test

      - name: pytest
        run: poetry run pytest
        working-directory: ./
